version: 2.1


orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
#workflows:
#  main:
#    jobs:
#      - build:
#          context: sonarcloud

jobs:
  build:
    docker:

      - image: circleci/python:3.6.4
#        environment:
#          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout

      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: install dependencies
          command: |
            pwd
            which python
            ls
            sudo pip install pipenv
#            python3 -m venv venv
#            . venv/bin/activate

            pipenv install
#            pipenv lock
            ls -al

#      - run: #original dependencies
#          name: install dependencies
#          command: |
#            pwd
#            ls
#            python3 -m venv venv
#            . venv/bin/activate
#
#            pip install -r requirements.txt
##            pip lock
#            ls -al

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

      - run:
          name: run unit tests
          command: |
            wihch python
            . venv/bin/activate
            python -m pytest -v test/test_configuration_of_optimiser.py #approach 3
            coverage run aristoptimiser/OptimiserConfigurator.py
            coverage report -m
            coverage html
            coverage xml -i
      - store_artifacts:
          path: htmlcov

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_test_results:
          path: test-reports

      - sonarcloud/scan

